# Generated by Django 5.0.4 on 2024-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_img_url', models.URLField()),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('genre', models.CharField(max_length=200)),
                ('external_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
