# Generated by Django 5.0.4 on 2024-05-08 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='chat_enabled',
        ),
        migrations.RemoveField(
            model_name='room',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='room',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
