# Generated by Django 5.0.4 on 2024-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_chat_enabled_remove_room_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='playback_time',
            field=models.FloatField(default=0.0),
        ),
    ]
