# Generated by Django 5.0.4 on 2024-05-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_is_live_room_live_video_url_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
